ansible_cmdb/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('user:login')), name='index'),
    path('user/', include('user.urls')),
    path('host/', include('host.urls')),
    path('ansibleapi/', include('api.urls')),
]

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path(r'', views.ansible_index,name='ansible_index'),
    path(r'result/', views.ansible_api,name='ansible_api'),
    path(r'listhost/', views.display,name='display'),
]

host/urls.py
#encoding: utf-8

from django.urls import path

from . import views

app_name = 'host'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    #path('fenye/', views.fenye, name='fenye'),
    path('search/', views.search, name='search'),
    path('homepage/', views.homepage, name='homepage'),
    path('edit/(?P<id>\d+)/', views.edit, name='edit'),
    path('update/(?P<id>\d+)/', views.update, name='update'),
    #path('addresult/', views.addresult, name='addresult'),
    path('detalinfo/(?P<id>\d+)/', views.detalinfo, name='detalinfo'),
]

host/models.py
#encoding: utf-8

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import timedelta

class Host(models.Model):
    name = models.CharField(verbose_name='主机名', max_length=256, default='', null=False)
    os = models.CharField(verbose_name='操作系统', max_length=256, default='', null=False)
    os_v = models.CharField(verbose_name='操作系统版本', max_length=256, default='', null=False)
    ip = models.GenericIPAddressField(verbose_name='IP地址')
    p_ip = models.GenericIPAddressField(verbose_name='p_IP地址')
    arch = models.CharField(verbose_name='架构', max_length=32, default='', null=False)
    mem = models.BigIntegerField(verbose_name='内存', default=0, null=False)
    cpu = models.IntegerField(verbose_name='CPU', default=0, null=False)
    remark = models.TextField(verbose_name='备注', default='', blank=True)
    created_time = models.DateTimeField(verbose_name='发现时间', auto_now_add=True, null=False)
    last_time = models.DateTimeField(verbose_name='最后发现时间', auto_now=True, null=False)

    def is_online(self):
        return timezone.now() - self.last_time < timedelta(hours=6)

    @classmethod
    def create_or_replace(cls, name, ip, arch, os, mem, cpu,p_ip,os_v):
        obj = None
        try:
            obj = Host.objects.get(p_ip=p_ip)
        except ObjectDoesNotExist as e:
            obj = Host()
            obj.p_ip = p_ip
        obj.name = name
        obj.arch = arch
        obj.os = os
        obj.mem = mem
        obj.cpu = cpu
        obj.ip = ip
        obj.os_v = os_v

        obj.save()
        return obj

    def __str__(self):
        return '{0}({1})'.format(self.name, self.ip)

host/views.py
#encoding: utf-8

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from collections import namedtuple
from ansible.parsing.dataloader import DataLoader
from ansible.vars.manager import VariableManager
from ansible.inventory.manager import InventoryManager
from ansible.playbook.play import Play
from ansible.executor.task_queue_manager import TaskQueueManager
from ansible.plugins.callback import CallbackBase
from django.core.management.base import BaseCommand
import ansible.constants as C
import json
import os
from collections import namedtuple
import shutil

from django.conf import settings

from .models import Host



class ModelResultsCollector(CallbackBase):
    """
    重写callbackBase类的部分方法
    """
    def __init__(self, *args, **kwargs):
        super(ModelResultsCollector, self).__init__(*args, **kwargs)
        self.host_ok = {}
        self.host_unreachable = {}
        self.host_failed = {}
        self.host_fact ={}
    def v2_runner_on_unreachable(self, result):
        self.host_unreachable[result._host.get_name()] = result
    def v2_runner_on_ok(self, result):
        self.host_ok[result._host.get_name()] = result
    def v2_runner_on_failed(self, result,ignore_errors=False):
        self.host_failed[result._host.get_name()] = result



class AnsibleApi(object):
    def __init__(self):
        self.Options = namedtuple('Options',
                     ['connection',
                      'remote_user',
                      'ask_sudo_pass',
                      'verbosity',
                      'ack_pass',
                      'module_path',
                      'forks',
                      'become',
                      'become_method',
                      'become_user',
                      'check',
                      'listhosts',
                      'listtasks',
                      'listtags',
                      'syntax',
                      'sudo_user',
                      'sudo',
                      'diff'])
        self.options = self.Options(connection='smart',
                       remote_user=None,
                       ack_pass=None,
                       sudo_user=None,
                       forks=5,
                       sudo=None,
                       ask_sudo_pass=False,
                       verbosity=5,
                       module_path=None,
                       become=None,
                       become_method=None,
                       become_user=None,
                       check=False,
                       diff=False,
                       listhosts=None,
                       listtasks=None,
                       listtags=None,
                       syntax=None)

        self.loader = DataLoader()
        self.inventory = InventoryManager(loader=self.loader, sources=os.path.join(settings.BASE_DIR, 'etc', 'hosts'))
        self.variable_manager = VariableManager(loader=self.loader, inventory=self.inventory)
        self.callback = ModelResultsCollector()
        self.passwords = dict()
    
    def runansible(self,host_list):
        
        play_source = {
            'name' : 'fact',
            'hosts' : host_list,
            'gather_facts' : 'no',
            'tasks' : [
                {
                    'name' : 'fact',
                    'setup' : ''
                }
            ],
        }
    
        play = Play().load(play_source, variable_manager=self.variable_manager, loader=self.loader)    
        tqm = TaskQueueManager(
           inventory=self.inventory,
           variable_manager=self.variable_manager,
           loader=self.loader,
           options=self.options,
           passwords=self.passwords,
           stdout_callback=self.callback,
           )

        result = tqm.run(play)
        result = tqm.run(play)
        result_raw = {'success':{},'failed':{},'unreachable':{}}
        for host,result in self.callback.host_ok.items():
            result_raw['success'][host] = result._result
        for host,result in self.callback.host_failed.items():
            result_raw['failed'][host] = result._result
        for host,result in self.callback.host_unreachable.items():
            result_raw['unreachable'][host] = result._result

        sucess = list(result_raw['success'].keys())
        for i in sucess:
            dic=result_raw['success'][i]["ansible_facts"]
            arch=dic.get('ansible_architecture','')
            mem=dic.get('ansible_memtotal_mb',0)
            cpu=dic.get('ansible_processor_vcpus',0)
            os=dic.get('ansible_os_family','')
            ip=dic.get('ansible_default_ipv4',{}).get('address', '')
            p_ip=i              #公网IP
            name=dic.get('ansible_nodename',i)
            os_v = dic.get('ansible_distribution_version','')
            Host.create_or_replace(name, ip, arch, os, mem, cpu,p_ip,os_v)
           

        fail = list(result_raw['failed'].keys())
        for i in fail:
            arch=''
            mem=0
            cpu=0
            os=''
            ip=i
            p_ip=i
            name=''
            os_v=''
            Host.create_or_replace(name, ip, arch, os, mem, cpu,p_ip,os_v) 


        unreachable = list(result_raw['unreachable'].keys())
        for i in unreachable:
            arch=''
            mem=0
            cpu=0
            os=''
            ip=i
            p_ip=i
            name=''
            os_v=''
            Host.create_or_replace(name, ip, arch, os, mem, cpu,p_ip,os_v)
            print(unreachable)



@login_required
def index(request):
    return render(request, 'host/index.html', {'objects' : Host.objects.all()})


@login_required
def homepage(request):
    service=Host.objects.all()
    redhat=Host.objects.filter(os='RedHat')
    centos=Host.objects.filter(os='CentOS')
    s_count=len(service)
    r_count=len(redhat)
    c_count=len(centos)
    data = {'s_count':s_count,'r_count':r_count,'c_count':c_count}
    return render(request, 'host/homepage.html',data)

@login_required
def delete(request):
    pk = request.GET.get("pk", 0)
    Host.objects.filter(pk=pk).delete()
    return redirect(reverse('host:index'))

#add主机信息页面
@login_required
def add(request):
    return render(request, 'host/add.html')

#添加信息后跳转到index页面
@login_required
def addresult(request):
    if request.POST:
        name = request.POST['name']
        mem = request.POST['mem']
        cpu = request.POST['cpu']
        os = request.POST['os']
        ip = request.POST['ip']
        p_ip = request.POST['p_ip']
        arch = request.POST['arch']
        os_v = request.POST['os_v']
    Host.create_or_replace(name, ip, arch, os, mem, cpu,p_ip,os_v)
    return redirect(reverse('host:index'))

#show每个主机详细信息
@login_required
def detalinfo(request,id):
    #pk = request.GET.get("id", 0)
    data=Host.objects.get(id=str(id))
    return render(request, 'host/info.html',{'data' : data})

#edit主机信息
@login_required
def edit(request,id):
    #pk = request.GET.get("id", 0)
    data=Host.objects.get(id=str(id))
    return render(request, 'host/edit.html',{'data' : data})



#update主机信息
@login_required
def update(request,id):
    data=Host.objects.get(id=str(id))
    ip=data.p_ip
    host_list=ip
    a = AnsibleApi()
    a.runansible(host_list)
    
    return redirect(reverse('host:index'))


#search主机信息
@login_required
def search(request):
    if request.GET:
        ip = request.GET['ip']
        data = Host.objects.filter(name__contains=ip)
        if data.count() == 0:
            data = Host.objects.filter(p_ip__contains=ip)
    return render(request, 'host/index.html', {'objects' : data})

host/templates/host/add.html
{% extends "base.html" %}
{% block content %}
<head>
<meta charset="utf-8">
<title>add</title>

 <style>
        label{
            display: inline-block;
            width: 100px;
            text-align: right;
        }
        div{
            padding: 5px 0;
        }
    </style>  

</head>
<body>
     

    <form action="/host/addresult/" method="post">
        {% csrf_token %}
      <p>
        <label for="主机名">主机名：</label>
        <input type="text" name="name">
      </p>
      <p>
        <label for="操作系统">操作系统：</label>
        <input type="text" name="os">
      </p>
      <p>
        <label for="IP地址">内网IP地址：</label>
        <input type="text" name="ip">
      </p>
      <p>
        <label for="P_IP地址">公网IP地址：</label>
        <input type="text" name="p_ip">
      </p>
      <p>
        <label for="架构">架构：</label>
        <input type="text" name="arch">
      </p>
      <p>
        <label for="内存">内存：</label>
        <input type="text" name="mem">
      </p>
      <p>
        <label for="CPU">CPU：</label>
        <input type="text" name="cpu">
      </p>
        <input type="submit" value="add">
    </form>

   </a>


</body>
{% endblock %}

host/templates/host/edit.html
{% extends "base.html" %}
{% block content %}
<head>
<meta charset="utf-8">
<title>edit</title>

    <style>
        label{
            display: inline-block;
            width: 100px;
            text-align: right;
        }
        div{
            padding: 5px 0;
        }
    </style>

</head>
<body>
     

    <form action="/host/addresult/" method="post">
        {% csrf_token %}


      <p>
        <label for="主机名">主机名：</label>
        <input  type="text" name="name" value={{ data.name }}>
      </p>
      <p>
        <label for="操作系统">操作系统：</label>
        <input type="text" name="os" value={{ data.os }}>
      </p>
      <p>
        <label for="操作系统版本">操作系统版本：</label>
        <input type="text" name="os_v" value={{ data.os_v }}>
      </p>

      <p>
        <label for="IP地址">内网IP地址：</label>
        <input type="text" name="ip" value={{ data.ip }}>
      </p>
      <p>
        <label for="P_IP地址">公网IP地址：</label>
        <input type="text" name="p_ip" value={{ data.p_ip }}>
      </p>
      <p>
        <label for="架构">架构：</label>
        <input type="text" name="arch" value={{ data.arch }}>
      </p>
      <p>
        <label for="内存">内存：</label>
        <input type="text" name="mem" value={{ data.mem }}>
      </p>
      <p>
        <label for="CPU">CPU：</label>
        <input type="text" name="cpu" value={{ data.cpu }}>
      </p>
        <input type="submit" value="save" name="_save">
    </form>
   </a>
   

</body>
{% endblock %}

host/templates/host/homepage.html
{% extends "base.html" %}
{% block content %}
<head>
<meta charset="utf-8">
<title>info</title>
</head>
<body>
     
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <table class="table table-bordered table-hover table-sm" id="platform">
                    <thead class="thead-light">
                        <tr>
                            <th>主机数量</th>
                            <th>CentOS数量</th>
                            <th>RedHat数量</th>
                        </tr>
                    </thead>
                    <tbody>
                            <tr>
                                <td> {{ s_count }}</td>
                                <td> {{ c_count }}</td>
                                <td> {{ r_count }}</td>
                            </tr>
</body>     
{% endblock %}

host/templates/host/index.html
{% extends "base.html" %}

{% block title %}主机管理{% endblock %}
{% block expanded_host %}is-expanded{% endblock %}
{% block active_host_cloud %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <table class="table table-bordered table-hover table-sm" id="platform">
                    <thead class="thead-light">
                        <tr>
                            <th>公网IP</th>
                            <th>内网IP</th>
                            <th>主机名</th>
                            <th>操作系统</th>
                            <th>配置(CPU/内存)</th>
                            <th>架构</th>
                            <th>发现时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
  
            
             <form  action="{% url 'host:search' %}" method="GET">
               <div class="col-md-3"><input type="text" class="form-control" name='ip' placeholder="主机名、IP" required></div>
               <button class="btn btn-sm btn-primary" type="submit">查询</button>
             </form>
             <a href="{% url 'host:add' %}" button type="button" class="btn btn-sm btn-primary">&nbsp;添加</a> 
     
                    
                    
                                         
     
                      

                        {% for object in objects %}
                            <tr>
                                <td>
                                <a href="{% url 'host:detalinfo'  id=object.id %}"  data-id="{{ object.id }}">{{ object.p_ip}}</a>
                                </td>
                                <td>{{ object.ip }}</td>
                                <td>{{ object.name }}</td>
                                <td>{{ object.os }}</td>
                                <td>{{ object.cpu }} 核 / {{ object.mem }} MB</td>
                                <td>{{ object.arch }}</td>
                                <td>{{ object.created_time|date:'Y-m-d H:i:s' }}</td>
                                <td>
                                    <a class="btn btn-sm btn-danger btn-delete" role="button" data-id="{{ object.id }}" data-name="{{ object.ip}}({{ object.name }})" data-toggle="tooltip" title="删除"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                    <a href="{% url 'host:edit'  id=object.id %}"  data-id="{{ object.id }}" button type="button" class="btn btn-sm btn-sucess" title="编辑"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    <a href="{% url 'host:update'  id=object.id %}"  data-id="{{ object.id }}" button type="button" class="btn btn-sm btn-sucess" title="刷新"><i class="fa fa-refresh" aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr><td colspan="6">暂无数据</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a class="btn btn-sm btn-danger  asset_all_del">批量删除</a>







            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block js %}
jQuery(document).ready(function() {
    jQuery('a.btn-delete').on('click', function() {
        var id = jQuery(this).data("id"), name= jQuery(this).data("name");
        if(confirm("确认删除主机记录:" + name)) {
            window.location.replace("{% url 'host:delete' %}?pk=" + id);
        }
    });
});
{% endblock %}

host/templates/host/info.html
{% extends "base.html" %}
{% block content %}
<head>
<meta charset="utf-8">
<title>info</title>
</head>
<body>
     


<p>
 主机名：{{ data.name }}
</p>
<p>
 公网IP：{{ data.p_ip }}
</p>
<p>
 内网IP：{{ data.ip }}
</p>
<p>
 操作系统：{{ data.os }}
</p>
<p>
 操作系统版本：{{ data.os_v }}
</p>
<p>
 CPU：{{ data.cpu }}
</p>
<p>
 内存：{{ data.mem }}
</p>
<p>
 架构：{{ data.arch }}
</p>


</body>
{% endblock %}