ansible_cmdb/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('user:login')), name='index'),
    path('user/', include('user.urls')),
    path('host/', include('host.urls')),
    path('ansibleapi/', include('api.urls')),
]

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path(r'', views.ansible_index,name='ansible_index'),
    path(r'result/', views.ansible_api,name='ansible_api'),
    path(r'listhost/', views.display,name='display'),
]

host/urls.py
#encoding: utf-8

from django.urls import path

from . import views

app_name = 'host'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    #path('fenye/', views.fenye, name='fenye'),
    path('search/', views.search, name='search'),
    path('homepage/', views.homepage, name='homepage'),
    path('edit/(?P<id>\d+)/', views.edit, name='edit'),
    path('update/(?P<id>\d+)/', views.update, name='update'),
    #path('addresult/', views.addresult, name='addresult'),
    path('detalinfo/(?P<id>\d+)/', views.detalinfo, name='detalinfo'),
]

user/urls.py
#encoding: utf-8

from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login/', views.login_view, name='login2'),
    path('logout/', views.logout_view, name='logout'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %}主机管理系统{% endblock %}</title>

        <link href="{% static 'plugins/bootstrap-4.1.3/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/vali-admin/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/DataTables-1.10.18/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
        {% block links %} {% endblock %}
        <style type="text/css">
            {% block style %}{% endblock %}
        </style>
    </head>
    <body class="app sidebar-mini rtl sidenav-toggled">
        <header class="app-header">
            <a class="app-header__logo" href="javascript:void(0);">CMDB</a>
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <ul class="app-nav">
                <nav class="navbar navbar-light">
                    <span class="navbar-text" style="font-weight: bolder;">
                        当前登陆用户: {{ request.user.username }}
                    </span>
                </nav>
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu">
                        <i class="fa fa-user fa-lg"></i>
                    </a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="page-user.html">
                                <i class="fa fa-user fa-lg"></i>修改密码
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'user:logout' %}">
                                <i class="fa fa-sign-out fa-lg"></i>退出登录
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item " href="{% url 'host:homepage' %}">
                        <i class="app-menu__icon fa fa-dashboard"></i>
                        <span class="app-menu__label">首页</span>
                    </a>
                </li>

             <li>
            </ul>

            <ul class="app-menu">
                <li>
                    <a class="app-menu__item {% block active_host %}{% endblock %}" href="{% url 'host:index' %}">
                        <i class="app-menu__icon fa fa-laptop"></i>
                        <span class="app-menu__label">主机管理</span>
                    </a>
                </li>
               
             <li>
            </ul>
         
          <ul class="app-menu">
                <li>
                    <a class="app-menu__item"   href="{% url 'api:ansible_index' %}">
                       <i class="app-menu__icon fa fa-laptop"></i>
                        <span class="app-menu__label">Ansible</span>
                    </a>
                </li>

             <li>
            </ul>
        </aside>




        <main class="app-content">
            {% block content %}{% endblock %}
        </main>
        {% block dialogs %}{% endblock %}
        <script type="text/javascript" src="{% static 'plugins/jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/popper.js-1.14.4/umd/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-4.1.3/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/vali-admin/js/main.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/pace-1.0.0/pace.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/DataTables-1.10.18/js/jquery.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/DataTables-1.10.18/js/dataTables.bootstrap4.min.js' %}"></script>
        {% block scripts %}{% endblock %}
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery.extend(jQuery.fn.dataTable.defaults, {
                    language: {
                        url: "{% static 'json/datatable_zh_CN.json' %}"
                    }
                });

                {% block js %}{% endblock %}
            });

        </script>
    </body>
</html>